### ISSUE TITLE
Include a LICENSE file

### ISSUE THREAD

**Issue by jaydenkieran** [Cheeselab/DecoraterBot#11]
How else do we know what license this project uses?

**Comment by AraHaan** [comment]
I personally been thinking the same recently. However I would have to copy and paste the data from the py files. Note: there are a few cuss words in it because I was mad when someone was stealing credit for my code. Sorry about that so I plan to change them eventually.

**Comment by AraHaan** [comment]
Added in 137c0b373f85ba507f591f479b4e351dba399259

**Comment by gdude2002** [comment]
The bundled LICENSE file is not a recognised open source license; distributing Python as well as the bytecode-compiled libraries alongside your bot breaks the licenses that apply to them.

Not only do you need an open-source license that is compatible with them, but you need to credit the authors of them as well.

Perhaps you should consider doing some research, and maybe not bundling Python and these dependencies with the bot. Python is easy enough to install anyway, and it comes with this great package manager called `pip` - you should check it out!

**Comment by AraHaan** [comment]
Actually the stuff is fine. Nothing is broken as they have not changed (except for Discord.py) And therefore its fine as it is. Also portability with the embed version is fine as well.

**Comment by Paladinleeds** [comment]
As this issue is not yet resolved I am re-opening this ticket. Copyright is a complex issue and I would encourage helpful comments detailing how to handle this.

**Comment by jaydenkieran** [comment]
I've made a follow-up comment to this issue here: https://github.com/Cheeselab/DecoraterBot/issues/17#issuecomment-244227880

Feel free to discuss.
