### ISSUE TITLE
prune command currently broken.

### ISSUE THREAD

**Issue by AraHaan** [Cheeselab/DecoraterBot#17]
Sorry, guys I think my implimentation to make things simpler via the decorator replacement I did earlier today made python mess up.

**Comment by AraHaan** [comment]
So in other words I might have to sadler revert it to the way it was before. I did however notice some thigns wrong with the logs module too.

**Comment by AraHaan** [comment]
Also further Note: I might make some of the core modules into pyd compatible if they user / coder perfers making them pyd's (They can help hide some traceback lines on modules that do not really have the errors and thereby shortens the exception(s) some.

However the folowing files must never be made pyd's

> BotvoiceCommands.py

> BotCommands.py

> Ignore.py (as gets exceptions sometimes too)

Even with my Error handler thigns can get exceptions. Granted I do like to fix every last one. sometimes I have to revert things too. (sometimes things work but breaks other things making me revert it).

**Comment by The-Pathogen** [comment]
Yo senpai dawg notice me bruh

**Comment by AraHaan** [comment]
ok so looks like a new roadmap

- [ ] Revert the changes made in ``#a7b1c58e679d23819914780cb0cc7c206864838d``

**Comment by The-Pathogen** [comment]
Wew

**Comment by AraHaan** [comment]
😛Reverting now..

**Comment by The-Pathogen** [comment]
👍

**Comment by AraHaan** [comment]
btw I will have to change a few lins in BotLogs as I now know those can cause issues. LOL

**Comment by The-Pathogen** [comment]
Rip
