### ISSUE TITLE
Path separator constant

### ISSUE THREAD

**Issue by AdamJonesay** [Cheeselab/DecoraterBot#7]
``
Traceback (most recent call last):
  File "DecoraterBot.py", line 43, in <module>
    import DecoraterBotCore
ImportError: No module named 'DecoraterBotCore'
``
I noticed in DecoraterBot.py on line 40 a reference to `"\\resources\\Dependencies"`. Shouldn't this be using path seperator constant?
This seems like an awesome bot, but I'd love cross platform support.

**Comment by AraHaan** [comment]
What OS are you using?

**Comment by AraHaan** [comment]
hmm seems I could do ``os.sep`` on anything with a ``\\``

**Comment by AraHaan** [comment]
Ok Path Separators are in Commit <still in proccess of commiting it>.

**Comment by AraHaan** [comment]
Ok so @AdamJonesay if you could help can you go on a spree to copy your python binaries and place them in the folder of your fork and pull request those so I can have the python binaries to your platform. Also even if I fixed DecoraterBot.py it would not work with the windows specific binaries that it depends on. So this means I need binaries to any build of python 1st and then add support for it based on their binaries and sys.platform values. (sorry about this but there are system specific thigns it has to do like I am sure linux and other platforms dont have a ``kernel32.dll`` file.

**Comment by AdamJonesay** [comment]
I am using the latest version of python3.5 (python-3.5.2-1) on arch linux.
``Linux petunia 4.6.4-1-ARCH #1 SMP PREEMPT Mon Jul 11 19:12:32 CEST 2016 x86_64 GNU/Linux``
sys.platform returns linux. I'll get to work copying my binaries. Not sure exactly where they're located, but I'll figure it out.

**Comment by AraHaan** [comment]
hmm I did hear rumors that they could be in somewhere in ``/usr/bin/``.

**Comment by AraHaan** [comment]
Well looks like I found a place to download the Linux Python Binaries for 3.5.2 however it needs some testing. Sadly you will have to make some scripts and pull request them for linux users to execute via command line by double clicking them just like I can in Windows.

**Comment by AraHaan** [comment]
Well come to think of it this is almost complete all this needs now is different zip files as the magic of the pyc files within them are different from the windows ones.

**Comment by AraHaan** [comment]
Hmm come to think of it it would not be possible to use the linux interpreter like the windows one is. So that means I cant ship it.
