### ISSUE TITLE
The prune command should use the bulk deletion endpoint.

### ISSUE THREAD

**Issue by Roadcrosser** [Cheeselab/DecoraterBot#9]
Currently, the prune command takes a log of messages, and deletes each one seperately. The discord devs don't really like this, it's ratelimited and really slow.

Instead, a bulk deletion endpoint exists, allowing messages to be deleted much, much faster, and can easily be used with discord.py's [purge_from](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.purge_from) function.

Using the bulk deletion endpoint would also cause less ratelimits to happen, which is another plus.

**Comment by AraHaan** [comment]
I would but I would have to have someone to help me as I have not used the purge_from myself. Well I tried to do it a few test copies but failed to get it to work. That is why I did not make the change yet as I need to find out what lines to change and then make the needed edits. But yeah this was also planned.

**Comment by Roadcrosser** [comment]
Fixed in [a87a1ca](https://github.com/Cheeselab/DecoraterBot/commit/a87a1cad8a4c7bd941f6a42b5d38355ab89a3b94).
